config/routes.rb
Rails.application.routes.draw do
  resources :u6_tables
  resources :sgrna_targets
  resources :array_tables
  resources :array_positions
  resources :vector_tables
  resources :plant_notes
  resources :gp_notes
  resources :gene_csins
  resources :gene_athals
  resources :guide_tables
  get 'societal_acceptance/index'
  get 'societal_acceptance/acceptance'
  get 'info/index'
  resources :gene_studies
  resources :plant_tables
  resources :genotyping_tables
  resources :gene_tables
  get 'contact/form'
  get 'guide/guides'
  get 'gene/genes'
  get 'plant/plants'
  resources :posts
  root :to => 'home#index'
  get '/search' => 'home#search', :as => 'search_page'
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/array_position.rb
class ArrayPosition < ApplicationRecord
end

app/models/array_table.rb
class ArrayTable < ApplicationRecord
end

app/models/gene_athal.rb
class GeneAthal < ApplicationRecord
end

app/models/gene_csin.rb
class GeneCsin < ApplicationRecord
end

app/models/gene_study.rb
class GeneStudy < ApplicationRecord
end

app/models/gene_table.rb
class GeneTable < ApplicationRecord
end

app/models/gp_note.rb
class GpNote < ApplicationRecord
end

app/models/guide_table.rb
class GuideTable < ApplicationRecord
end

app/models/plant_note.rb
class PlantNote < ApplicationRecord
end

app/models/plant_table.rb
class PlantTable < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/sgrna_target.rb
class SgrnaTarget < ApplicationRecord
end

app/models/u6_table.rb
class U6Table < ApplicationRecord
end

app/models/vector_table.rb
class VectorTable < ApplicationRecord
end

app/controllers/gene_studies_controller.rb
class GeneStudiesController < ApplicationController
  before_action :set_gene_study, only: %i[ show edit update destroy ]

  # GET /gene_studies or /gene_studies.json
  def index
    redirect_to root_path
    @gene_studies = GeneStudy.all
  end

  # GET /gene_studies/1 or /gene_studies/1.json
  def show
    redirect_to root_path
  end

  # GET /gene_studies/new
  def new
    redirect_to root_path
    @gene_study = GeneStudy.new
  end

  # GET /gene_studies/1/edit
  def edit
    redirect_to root_path
  end

  # POST /gene_studies or /gene_studies.json
  def create
    @gene_study = GeneStudy.new(gene_study_params)

    respond_to do |format|
      if @gene_study.save
        format.html { redirect_to @gene_study, notice: "Gene study was successfully created." }
        format.json { render :show, status: :created, location: @gene_study }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gene_study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gene_studies/1 or /gene_studies/1.json
  def update
    respond_to do |format|
      if @gene_study.update(gene_study_params)
        format.html { redirect_to @gene_study, notice: "Gene study was successfully updated." }
        format.json { render :show, status: :ok, location: @gene_study }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gene_study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gene_studies/1 or /gene_studies/1.json
  def destroy
    redirect_to root_path
    @gene_study.destroy
    respond_to do |format|
      format.html { redirect_to gene_studies_url, notice: "Gene study was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gene_study
      @gene_study = GeneStudy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gene_study_params
      params.require(:gene_study).permit(:Gene_ID, :Study)
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gene_helper.rb
module GeneHelper
end

app/helpers/gene_studies_helper.rb
module GeneStudiesHelper
end

app/helpers/guide_helper.rb
module GuideHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/plant_helper.rb
module PlantHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/gene_studies/_form.html.erb
<%= form_with(model: gene_study) do |form| %>
  <% if gene_study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gene_study.errors.count, "error") %> prohibited this gene_study from being saved:</h2>

      <ul>
        <% gene_study.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Gene_ID %>
    <%= form.text_field :Gene_ID %>
  </div>

  <div class="field">
    <%= form.label :Study %>
    <%= form.text_field :Study %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gene_studies/edit.html.erb
<!--
<h1>Editing Gene Study</h1>

<%= render 'form', gene_study: @gene_study %>

<%= link_to 'Show', @gene_study %> |
<%= link_to 'Back', gene_studies_path %>
-->

app/views/gene_studies/index.html.erb
<!--

<h1>Gene Studies</h1>

<table>
<p id="notice"><%= notice %></p>
  <thead>
    <tr>
      <th>Gene id</th>
      <th>Study</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gene_studies.each do |gene_study| %>
      <tr>
        <td><%= gene_study.Gene_ID %></td>
        <td><%= gene_study.Study %></td>
        <td><%= link_to 'Show', gene_study %></td>
        <td><%= link_to 'Edit', edit_gene_study_path(gene_study) %></td>
        <td><%= link_to 'Destroy', gene_study, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gene Study', new_gene_study_path %>

-->

app/views/gene_studies/new.html.erb
<!--
<h1>New Gene Study</h1>

<%= render 'form', gene_study: @gene_study %>

<%= link_to 'Back', gene_studies_path %>

-->

app/views/gene_studies/show.html.erb
<!--
<p id="notice"><%= notice %></p>

<p>
  <strong>Gene id:</strong>
  <%= @gene_study.Gene_ID %>
</p>

<p>
  <strong>Study:</strong>
  <%= @gene_study.Study %>
</p>

<%= link_to 'Edit', edit_gene_study_path(@gene_study) %> |
<%= link_to 'Back', gene_studies_path %>

-->