config/routes.rb
Rails.application.routes.draw do
  resources :u6_tables
  resources :sgrna_targets
  resources :array_tables
  resources :array_positions
  resources :vector_tables
  resources :plant_notes
  resources :gp_notes
  resources :gene_csins
  resources :gene_athals
  resources :guide_tables
  get 'societal_acceptance/index'
  get 'societal_acceptance/acceptance'
  get 'info/index'
  resources :gene_studies
  resources :plant_tables
  resources :genotyping_tables
  resources :gene_tables
  get 'contact/form'
  get 'guide/guides'
  get 'gene/genes'
  get 'plant/plants'
  resources :posts
  root :to => 'home#index'
  get '/search' => 'home#search', :as => 'search_page'
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/array_position.rb
class ArrayPosition < ApplicationRecord
end

app/models/array_table.rb
class ArrayTable < ApplicationRecord
end

app/models/gene_athal.rb
class GeneAthal < ApplicationRecord
end

app/models/gene_csin.rb
class GeneCsin < ApplicationRecord
end

app/models/gene_study.rb
class GeneStudy < ApplicationRecord
end

app/models/gene_table.rb
class GeneTable < ApplicationRecord
end

app/models/gp_note.rb
class GpNote < ApplicationRecord
end

app/models/guide_table.rb
class GuideTable < ApplicationRecord
end

app/models/plant_note.rb
class PlantNote < ApplicationRecord
end

app/models/plant_table.rb
class PlantTable < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/sgrna_target.rb
class SgrnaTarget < ApplicationRecord
end

app/models/u6_table.rb
class U6Table < ApplicationRecord
end

app/models/vector_table.rb
class VectorTable < ApplicationRecord
end

app/controllers/gene_athals_controller.rb
class GeneAthalsController < ApplicationController
  before_action :set_gene_athal, only: %i[ show edit update destroy ]

  # GET /gene_athals or /gene_athals.json
  def index
    redirect_to root_path
    @gene_athals = GeneAthal.all
  end

  # GET /gene_athals/1 or /gene_athals/1.json
  def show
    redirect_to root_path
  end

  # GET /gene_athals/new
  def new
    redirect_to root_path
    @gene_athal = GeneAthal.new
  end

  # GET /gene_athals/1/edit
  def edit
    redirect_to root_path
  end

  # POST /gene_athals or /gene_athals.json
  def create
    redirect_to root_path
    @gene_athal = GeneAthal.new(gene_athal_params)

    respond_to do |format|
      if @gene_athal.save
        format.html { redirect_to @gene_athal, notice: "Gene athal was successfully created." }
        format.json { render :show, status: :created, location: @gene_athal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gene_athal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gene_athals/1 or /gene_athals/1.json
  def update
    redirect_to root_path
    respond_to do |format|
      if @gene_athal.update(gene_athal_params)
        format.html { redirect_to @gene_athal, notice: "Gene athal was successfully updated." }
        format.json { render :show, status: :ok, location: @gene_athal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gene_athal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gene_athals/1 or /gene_athals/1.json
  def destroy
    redirect_to root_path
    @gene_athal.destroy
    respond_to do |format|
      format.html { redirect_to gene_athals_url, notice: "Gene athal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gene_athal
      @gene_athal = GeneAthal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gene_athal_params
      params.require(:gene_athal).permit(:Gene_ID, :Orthogroup_genes_Athal)
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gene_athals_helper.rb
module GeneAthalsHelper
end

app/helpers/gene_helper.rb
module GeneHelper
end

app/helpers/guide_helper.rb
module GuideHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/plant_helper.rb
module PlantHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/gene_athals/_form.html.erb
<%= form_with(model: gene_athal) do |form| %>
  <% if gene_athal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gene_athal.errors.count, "error") %> prohibited this gene_athal from being saved:</h2>

      <ul>
        <% gene_athal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Gene_ID %>
    <%= form.text_field :Gene_ID %>
  </div>

  <div class="field">
    <%= form.label :Orthogroup_genes_Athal %>
    <%= form.text_field :Orthogroup_genes_Athal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gene_athals/edit.html.erb
<h1>Editing Gene Athal</h1>

<%= render 'form', gene_athal: @gene_athal %>

<%= link_to 'Show', @gene_athal %> |
<%= link_to 'Back', gene_athals_path %>

app/views/gene_athals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gene Athals</h1>

<table>
  <thead>
    <tr>
      <th>Gene id</th>
      <th>Orthogroup genes athal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gene_athals.each do |gene_athal| %>
      <tr>
        <td><%= gene_athal.Gene_ID %></td>
        <td><%= gene_athal.Orthogroup_genes_Athal %></td>
        <td><%= link_to 'Show', gene_athal %></td>
        <td><%= link_to 'Edit', edit_gene_athal_path(gene_athal) %></td>
        <td><%= link_to 'Destroy', gene_athal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gene Athal', new_gene_athal_path %>

app/views/gene_athals/new.html.erb
<h1>New Gene Athal</h1>

<%= render 'form', gene_athal: @gene_athal %>

<%= link_to 'Back', gene_athals_path %>

app/views/gene_athals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gene id:</strong>
  <%= @gene_athal.Gene_ID %>
</p>

<p>
  <strong>Orthogroup genes athal:</strong>
  <%= @gene_athal.Orthogroup_genes_Athal %>
</p>

<%= link_to 'Edit', edit_gene_athal_path(@gene_athal) %> |
<%= link_to 'Back', gene_athals_path %>