config/routes.rb
Rails.application.routes.draw do
  resources :u6_tables
  resources :sgrna_targets
  resources :array_tables
  resources :array_positions
  resources :vector_tables
  resources :plant_notes
  resources :gp_notes
  resources :gene_csins
  resources :gene_athals
  resources :guide_tables
  get 'societal_acceptance/index'
  get 'societal_acceptance/acceptance'
  get 'info/index'
  resources :gene_studies
  resources :plant_tables
  resources :genotyping_tables
  resources :gene_tables
  get 'contact/form'
  get 'guide/guides'
  get 'gene/genes'
  get 'plant/plants'
  resources :posts
  root :to => 'home#index'
  get '/search' => 'home#search', :as => 'search_page'
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/array_position.rb
class ArrayPosition < ApplicationRecord
end

app/models/array_table.rb
class ArrayTable < ApplicationRecord
end

app/models/gene_athal.rb
class GeneAthal < ApplicationRecord
end

app/models/gene_csin.rb
class GeneCsin < ApplicationRecord
end

app/models/gene_study.rb
class GeneStudy < ApplicationRecord
end

app/models/gene_table.rb
class GeneTable < ApplicationRecord
end

app/models/gp_note.rb
class GpNote < ApplicationRecord
end

app/models/guide_table.rb
class GuideTable < ApplicationRecord
end

app/models/plant_note.rb
class PlantNote < ApplicationRecord
end

app/models/plant_table.rb
class PlantTable < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/sgrna_target.rb
class SgrnaTarget < ApplicationRecord
end

app/models/u6_table.rb
class U6Table < ApplicationRecord
end

app/models/vector_table.rb
class VectorTable < ApplicationRecord
end

app/helpers/gene_helper.rb
module GeneHelper
end

app/helpers/guide_helper.rb
module GuideHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/plant_helper.rb
module PlantHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/shared/_infonavbar.html.erb
        <nav class="navbar navbar-standard navbar-light navbar-glass navbar-top sticky-kit navbar-expand-lg">
          <button class="btn navbar-toggler-humburger-icon navbar-toggler mr-1 mr-sm-3" type="button" data-bs-toggle="collapse" data-target="#navbarStandard" aria-controls="navbarStandard" aria-expanded="false" aria-label="Toggle Navigation"><span class="navbar-toggle-icon"><span class="toggle-line"></span></span></button>
<!---------------------------------------LOGO----------------------------------------->
          <a class="navbar-brand mr-1 mr-sm-3" href="<%= root_path %>">
            <div class="d-flex align-items-center"><%= image_tag "logos/logo.svg", class:"mr-2 filter-logo", width:"40" %><span class="text-sans-serif">CRISPR Citrus</span>
            </div>
          </a>
          
          <div class="collapse navbar-collapse" id="navbarStandard">
            <ul class="navbar-nav">
<!---------------------------------------PLANTS, GENES & GUIDES-----------------------------------------> 
              <li class="nav-item"><a class="nav-link" href="<%= plant_plants_path %>"><span class="mr-2 fas fa-leaf" role="img" aria-label="leaf"></span>Plants</a></li>
              <li class="nav-item"><a class="nav-link" href="<%= gene_genes_path %>"><span class="mr-2 fas fa-dna" role="img" aria-label="dna"></span>Genes</a></li>
              <li class="nav-item"><a class="nav-link" href="<%= guide_guides_path %>"><span class="mr-2 fas fa-bullseye" role="img" aria-label="dna"></span>Guides</a></li>
              <% if mobile_device != "mobile" %>
                    <li class="nav-item"><a class="nav-link" href="#!">|</a></li>
                <% elsif mobile_device == "mobile" %>
              <%end%>

<!---------------------------------------FURTHER INFO-----------------------------------------> 
              <li class="nav-item dropdown dropdown-on-hover"><a class="nav-link dropdown-toggle" id="navbarDropdownInfo" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Further info</a>
                <div class="dropdown-menu dropdown-menu-card" aria-labelledby="navbarDropdownInfo">
                  <div class="bg-white rounded-soft py-2">
                  
                  <%= link_to "Citrus and HLB", info_index_path(info: "hlb"), class:"dropdown-item fs-0" %>
                  <%= link_to "Selection of Target Genes", info_index_path(info: "target-genes"), class:"dropdown-item fs-0" %>
                  <%= link_to "CRISPR/Cas9 Gene Editing", info_index_path(info: "gene-editing"), class:"dropdown-item fs-0" %>
                  <%= link_to "Vectors", info_index_path(info: "vectors"), class:"dropdown-item fs-0" %>
                  <%= link_to "Creation of transgenic plants", info_index_path(info: "transgenic-plants"), class:"dropdown-item fs-0" %>
                  </div>
                </div>
              </li>
<!---------------------------------------SOCIETAL ACCEPTANCE-----------------------------------------> 
              <li class="nav-item dropdown dropdown-on-hover"><a class="nav-link dropdown-toggle" id="navbarDropdownSocietal" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Societal acceptance</a>
                <div class="dropdown-menu dropdown-menu-card" aria-labelledby="navbarDropdownSocietal">
                  <div class="bg-white rounded-soft py-2">
                  <%= link_to "Societal Acceptance of Gene-Editing", societal_acceptance_index_path(info: "acceptance"), class:"dropdown-item fs-0" %>
                  </div>
                </div>
              </li>
              <% if mobile_device == "mobile" %>
               <div class="nav-item"><a class="btn btn-outline-citrus border-2x rounded-pill mb-2" href="<%= contact_form_path %>">Contact</a></div>
              <%end%>
              <li>
              </li>
            </ul>
<!---------------------------------------SEARCH BOX-----------------------------------------> 
            <ul class="navbar-nav ml-auto">
              <div class="nav-item">
                <%= form_tag(search_page_path, :method => "get", class: 'search-box') do %>  
                  <form class="position-relative" data-bs-toggle="search" data-display="static">
                    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control search-input" %>  
                    <span class="fas fa-search search-box-icon"></span>
                  </div>
                  </form>  
                <% end %>
              </div>
<!---------------------------------------CONTACT-----------------------------------------> 
              <% if mobile_device != "mobile" %>
                <div class="nav-item"><a class="btn btn-outline-citrus border-2x rounded-pill ml-2" href="<%= contact_form_path %>">Contact</a></div>
              <%end%>
            </ul>
          </div>
        </nav>

app/views/shared/_navbar.html.erb
      <%# MAIN NAVBAR FOR INDEX PAGE %>
      
        <% if mobile_device != "mobile" %>
          <nav class="navbar navbar-standard navbar-expand-lg fixed-top navbar-dark navbar-theme">
          <% elsif mobile_device == "mobile" %>
          <nav class="navbar navbar-standard navbar-expand-lg fixed-top navbar-dark navbar-theme-mobile" style="background-color: rgba(11, 23, 39, 0.5);">
        <%end%>
        <div class="container"><%= link_to "CRISPR Citrus", root_path, class: "navbar-brand text-black" %>
          <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-target="#navbarStandard" aria-controls="navbarStandard" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse scrollbar perfect-scrollbar" id="navbarStandard">
            <ul class="navbar-nav">

            <%# PATHS %>
              <li class="nav-item"><a class="nav-link" href="<%= plant_plants_path %>"><span class="mr-2 fas fa-leaf" role="img" aria-label="leaf"></span>Plants</a></li>
              <li class="nav-item"><a class="nav-link" href="<%= gene_genes_path %>"><span class="mr-2 fas fa-dna" role="img" aria-label="dna"></span>Genes</a></li>
              <li class="nav-item"><a class="nav-link" href="<%= guide_guides_path %>"><span class="mr-2 fas fa-bullseye" role="img" aria-label="dna"></span>Guides</a></li>
            
            <%# Further Info %>
            <% if mobile_device != "mobile" %>
              <li class="nav-item"><a class="nav-link" href="#!">|</a></li>
              <% elsif mobile_device == "mobile" %>
            <%end%>
              <li class="nav-item dropdown dropdown-on-hover"><a class="nav-link dropdown-toggle" id="navbarDropdownInfo" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Further info</a>
                <div class="dropdown-menu dropdown-menu-card" aria-labelledby="navbarDropdownInfo">
                  <div class="bg-black rounded-soft py-2">
                  <%= link_to "Citrus and HLB", info_index_path(info: "hlb"), class:"dropdown-item fs-0" %>
                  <%= link_to "Selection of Target Genes", info_index_path(info: "target-genes"), class:"dropdown-item fs-0" %>
                  <%= link_to "CRISPR/Cas9 Gene Editing", info_index_path(info: "gene-editing"), class:"dropdown-item fs-0" %>
                  <%= link_to "Vectors", info_index_path(info: "vectors"), class:"dropdown-item fs-0" %>
                  <%= link_to "Creation of transgenic plants", info_index_path(info: "transgenic-plants"), class:"dropdown-item fs-0" %>
                  </div>
                </div>
              </li>

              <li class="nav-item dropdown dropdown-on-hover"><a class="nav-link dropdown-toggle" id="navbarDropdownSocietal" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Societal acceptance</a>
                <div class="dropdown-menu dropdown-menu-card" aria-labelledby="navbarDropdownSocietal">
                  <div class="bg-black rounded-soft py-2">
                  <%= link_to "Societal Acceptance of Gene-Editing", societal_acceptance_index_path(info: "acceptance"), class:"dropdown-item fs-0" %>
                  </div>
                </div>
              </li>
              
            </ul>
            <%# CONTACT %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a class="btn btn-outline-light border-2x rounded-pill" href="<%= contact_form_path %>">Contact</a></li>
            </ul>
          </div>
        </div>
      </nav>