config/routes.rb
Rails.application.routes.draw do
  resources :u6_tables
  resources :sgrna_targets
  resources :array_tables
  resources :array_positions
  resources :vector_tables
  resources :plant_notes
  resources :gp_notes
  resources :gene_csins
  resources :gene_athals
  resources :guide_tables
  get 'societal_acceptance/index'
  get 'societal_acceptance/acceptance'
  get 'info/index'
  resources :gene_studies
  resources :plant_tables
  resources :genotyping_tables
  resources :gene_tables
  get 'contact/form'
  get 'guide/guides'
  get 'gene/genes'
  get 'plant/plants'
  resources :posts
  root :to => 'home#index'
  get '/search' => 'home#search', :as => 'search_page'
  
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/array_position.rb
class ArrayPosition < ApplicationRecord
end

app/models/array_table.rb
class ArrayTable < ApplicationRecord
end

app/models/gene_athal.rb
class GeneAthal < ApplicationRecord
end

app/models/gene_csin.rb
class GeneCsin < ApplicationRecord
end

app/models/gene_study.rb
class GeneStudy < ApplicationRecord
end

app/models/gene_table.rb
class GeneTable < ApplicationRecord
end

app/models/gp_note.rb
class GpNote < ApplicationRecord
end

app/models/guide_table.rb
class GuideTable < ApplicationRecord
end

app/models/plant_note.rb
class PlantNote < ApplicationRecord
end

app/models/plant_table.rb
class PlantTable < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/sgrna_target.rb
class SgrnaTarget < ApplicationRecord
end

app/models/u6_table.rb
class U6Table < ApplicationRecord
end

app/models/vector_table.rb
class VectorTable < ApplicationRecord
end

app/controllers/guide_tables_controller.rb
class GuideTablesController < ApplicationController
  before_action :set_guide_table, only: %i[ show edit update destroy ]

  # GET /guide_tables or /guide_tables.json
  def index
    @guide_tables = GuideTable.all
  end

  # GET /guide_tables/1 or /guide_tables/1.json
  def show
  end

  # GET /guide_tables/new
  def new
    @guide_table = GuideTable.new
  end

  # GET /guide_tables/1/edit
  def edit
  end

  # POST /guide_tables or /guide_tables.json
  def create
    @guide_table = GuideTable.new(guide_table_params)

    respond_to do |format|
      if @guide_table.save
        format.html { redirect_to @guide_table, notice: "Guide table was successfully created." }
        format.json { render :show, status: :created, location: @guide_table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guide_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guide_tables/1 or /guide_tables/1.json
  def update
    respond_to do |format|
      if @guide_table.update(guide_table_params)
        format.html { redirect_to @guide_table, notice: "Guide table was successfully updated." }
        format.json { render :show, status: :ok, location: @guide_table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guide_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guide_tables/1 or /guide_tables/1.json
  def destroy
    @guide_table.destroy
    respond_to do |format|
      format.html { redirect_to guide_tables_url, notice: "Guide table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guide_table
      @guide_table = GuideTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guide_table_params
      params.require(:guide_table).permit(:sgRNA_ID, :Sequence, :Orthologs_targeted)
    end
end

app/helpers/gene_helper.rb
module GeneHelper
end

app/helpers/guide_helper.rb
module GuideHelper
end

app/helpers/guide_tables_helper.rb
module GuideTablesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/plant_helper.rb
module PlantHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/guide_tables/_form.html.erb
<%= form_with(model: guide_table) do |form| %>
  <% if guide_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guide_table.errors.count, "error") %> prohibited this guide_table from being saved:</h2>

      <ul>
        <% guide_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sgRNA_ID %>
    <%= form.text_field :sgRNA_ID %>
  </div>

  <div class="field">
    <%= form.label :Sequence %>
    <%= form.text_field :Sequence %>
  </div>

  <div class="field">
    <%= form.label :Orthologs_targeted %>
    <%= form.text_field :Orthologs_targeted %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guide_tables/edit.html.erb
<!--
<h1>Editing Guide Table</h1>

<%= render 'form', guide_table: @guide_table %>

<%= link_to 'Show', @guide_table %> |
<%= link_to 'Back', guide_tables_path %>

-->

app/views/guide_tables/index.html.erb
<!--
<p id="notice"><%= notice %></p>

<h1>Guide Tables</h1>

<table>
  <thead>
    <tr>
      <th>Sgrna id</th>
      <th>Sequence</th>
      <th>Orthologs targeted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guide_tables.each do |guide_table| %>
      <tr>
        <td><%= guide_table.sgRNA_ID %></td>
        <td><%= guide_table.Sequence %></td>
        <td><%= guide_table.Orthologs_targeted %></td>
        <td><%= link_to 'Show', guide_table %></td>
        <td><%= link_to 'Edit', edit_guide_table_path(guide_table) %></td>
        <td><%= link_to 'Destroy', guide_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guide Table', new_guide_table_path %>

-->

app/views/guide_tables/new.html.erb
<!--
<h1>New Guide Table</h1>

<%= render 'form', guide_table: @guide_table %>

<%= link_to 'Back', guide_tables_path %>

-->

app/views/guide_tables/show.html.erb
<!--
<p id="notice"><%= notice %></p>

<p>
  <strong>Sgrna id:</strong>
  <%= @guide_table.sgRNA_ID %>
</p>

<p>
  <strong>Sequence:</strong>
  <%= @guide_table.Sequence %>
</p>

<p>
  <strong>Orthologs targeted:</strong>
  <%= @guide_table.Orthologs_targeted %>
</p>

<%= link_to 'Edit', edit_guide_table_path(@guide_table) %> |
<%= link_to 'Back', guide_tables_path %>
-->